{{- if $.Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "gitlab.serviceAccount.name" . }}
rules:
{{- if $.Values.rbac.role.rules }}
{{- toYaml $.Values.rbac.role.rules | nindent 2 }}
{{- end -}}
{{- end }}
