### Geo Primary
global:
  # must match versions to Omnibus
  gitlabVersion: 12.4.2
  # use our wildcard ssl, but with suffix
  hosts:
    hostSuffix: primary
    domain: example.com
  # configure DB connection
  psql:
    host: geo-1.db.example.com
    port: 5432
    password:
      secret: geo
      key: postgresql-password
  # configure geo (primary)
  geo:
    role: primary
# External DB, disable
postgresql:
  install: false

