## Geo Secondary
global:
  # must match versions to Omnibus
  gitlabVersion: 12.4.2
  # use our wildcard ssl, but with suffix
  hosts:
    hostSuffix: secondary
    domain: example.com
  # configure DB connection
  psql:
    host: geo-2.db.example.com
    port: 5432
    password:
      secret: geo
      key: postgresql-password
  # configure geo (secondary)
  geo:
    role: secondary
    psql:
      host: geo-2.db.example.com
      port: 5431
      password:
        secret: geo
        key: postgresql-password
# External DB, disable
postgresql:
  install: false

