{{- if .Values.global.kas.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "gitlab.standardLabels" . | nindent 4 }}
  annotations:
    {{- include "gitlab.deploymentAnnotations" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ template "name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
        {{- include "gitlab.podLabels" . | nindent 8 }}
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      {{- range $key, $value := .Values.annotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
    spec:
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if or .Values.serviceAccount.enabled .Values.global.serviceAccount.enabled }}
      serviceAccountName: {{ include "gitlab.serviceAccount.name" . }}
      automountServiceAccountToken: false
      {{- end }}
      containers:
        {{- include "gitlab.extraContainers" . | nindent 8 }}
        - name: {{ template "name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{ template "gitlab.imagePullPolicy" . }}
          args:
            - "--configuration-file=/etc/kas/config.yaml"
          ports:
            - containerPort: {{ .Values.service.internalPort }}
              name: {{ template "name" . }}
            - containerPort: {{ .Values.service.internalObservabilityPort }}
              name: {{ template "name" . }}-metrics
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: init-etc-kas
              mountPath: /etc/kas
              readOnly: true
            {{- include "gitlab.extraVolumeMounts" . | nindent 12 }}
      volumes:
      {{- include "gitlab.extraVolumes" . | nindent 6 }}
      - name: init-etc-kas
        projected:
          defaultMode: 0440
          sources:
            - configMap:
                name: {{ template "fullname" . }}
            - secret:
                name: {{ template "gitlab.kas.secret" . }}
                items:
                  - key: {{ template "gitlab.kas.key" . }}
                    path: .gitlab_kas_secret
{{- end }}
