# Need to set certmanager-issuer.email before templating
certmanager-issuer:
  email: me@example.com

# YAML anchor to demonstrate setting image.repository and image.tag
.custom: &custom
  image:
    repository: custom-repository
    tag: custom-tag

# --- Global settings ---

global:
  <<: *custom
  kubectl: *custom
  certificates: *custom
  grafana:
    enabled: true

# --- GitLab charts ---

gitlab:
  geo-logcursor: *custom
  gitaly:
    <<: *custom
    init: *custom
  gitlab-exporter:
    <<: *custom
    init: *custom
  gitlab-grafana: *custom
  gitlab-shell:
    <<: *custom
    init: *custom
  mailroom: *custom
  migrations:
    <<: *custom
    init: *custom
  operator: *custom
  sidekiq:
    <<: *custom
    init: *custom
  task-runner:
    <<: *custom
    init: *custom
  webservice:
    <<: *custom
    init: *custom
    workhorse:
      image: custom-repository
      tag: custom-tag

# --- Charts from requirements.yaml ---

certmanager:
  <<: *custom
  cainjector: *custom

gitlab-runner:
  image: custom-repository:custom-tag

minio:
  image: custom-repository
  imageTag: custom-tag
  init: *custom
  minioMc:
    image: custom-repository
    tag: custom-tag

nginx-ingress:
  controller: *custom
  defaultBackend: *custom

registry:
    <<: *custom
    init: *custom

postgresql:
  global:
    imageRegistry: custom-repository
  image:
    repository: custom-repository
    tag: 11-custom-tag # start with number to make checkConfig happy
  metrics: *custom

prometheus:
  server: *custom
  configmapReload: *custom

redis:
  global:
    imageRegistry: custom-repository
  <<: *custom
  metrics: *custom

upgradeCheck: *custom

grafana:
  <<: *custom
  sidecar:
    image: custom-repository:custom-tag
