#!/bin/sh
# This script will
# 1. create an EKS cluster
# 2. create an external IP
# 3. add a context to $HOME/.kube/config
# 5. Install tiller with a dedicated service account

set -e

# MacOS does not support readlink, but it does have perl
KERNEL_NAME=$(uname -s)
if [ "${KERNEL_NAME}" = "Darwin" ]; then
  SCRIPT_PATH=$(perl -e 'use Cwd "abs_path";use File::Basename;print dirname(abs_path(shift))' "$0")
else
  SCRIPT_PATH=$(dirname "$(readlink -f "$0")")
fi

source "${SCRIPT_PATH}/common.sh"

# Set default values
cluster_name=${CLUSTER_NAME-gitlab-cluster}
nodes=${NUM_NODES-2}
kubernetes_version=${CLUSTER_VERSION-1.10}
region="${REGION-us-east-2}"
node_type="${MACHINE_TYPE-m5.xlarge}"

function print_help(){
  cat <<EOF
Usage: ${0} ARGS (up|down)
-c NAME - Name of the cluster to use. Defaults to USERNAME-cluster
-n NODES - number of nodes to use. Defaults to 2
-k VERSION - Kubernetes version to use. Defaults to 1.10
-r REGION - Region to install the cluster in
-m TYPE - Type of nodes to use. Default m5.xlarge
up - create a cluster
down - delete a cluster
EOF
}

function do_up(){
  local cluster_name="${1}"
  local nodes="${2}"
  local kubernetes_version="${3}"
  local region="${4}"
  local node_type="${5}"

  eksctl create cluster --name="${cluster_name}" --nodes="${nodes}" --version="${kubernetes_version}" --region="${region}" --node-type="${node_type}"
  kubectl apply -f "${SCRIPT_PATH}/resources/helm.yaml"
  helm init --service-account helm
}

function do_down(){
  local cluster_name="${1}"

  eksctl delete cluster --wait --name ${cluster_name}
}

function do_list(){
  local cluster_name="${1}"

  eksctl get cluster ${cluster_name}
}

while getopts c:n:kr:m: opt
do
  case "${opt}" in
    c)
      cluster_name="${OPTARG}"
      ;;
    n)
      nodes="${OPTARG}"
      ;;
    k)
      kubernetes_version="${OPTARG}"
      ;;
    m)
      node_type="${OPTARG}"
      ;;
    r)
      region="${OPTARG}"
      ;;
    [?])
      print_help
      ;;
  esac
done
shift $((OPTIND -1))

validate_eks_required_tools

# Ensure we can connect to aws
if ! eksctl get cluster -v 0 > /dev/null
then
  >&2 echo "Cannot connect to AWS. Ensure credentials are configured"
  exit 1
fi

case ${1} in
  up)
    do_up "${cluster_name}" "${nodes}" "${kubernetes_version}" "${region}" "${node_type}"
    ;;
  down)
    do_down "${cluster_name}"
    ;;
  list)
    do_list "${2}"
    ;;
  *)
    print_help
    exit 1
esac
